philips:
  security:
    url: https://srv-kubnode-01.whebdc.com.br:9107/
  html2pdf:
    url: http://192.168.240.1:8888/
  tasy:
    voice:
      plugin: speech-recognition
      data-fill: true
      translate-by-llm: true
    component:
      advancedFilter:
        storage: DATABASE
      autocomplete:
        storage: DATABASE
      datasource:
        storage: DATABASE
      filter:
        storage: DATABASE
      text:
        storage: DATABASE
    security-enforced: false
    security-files:
      upload-limit: 0
    storage:
      filter:
        disabled: true
        include: .7z, .7zip, .avi, .bmp, .cda, .cih, .csv, .dat, .dbf, .dcm, .divx, .doc, .docm, .docx, .dotm, .dotx, .gif, .gz, .gzip, .htm, .html, .ics, .jpe, .jpeg, .jpg, .jrxml, .json, .key, .m4a, .m4b, .m4v, .mov, .mp3, .mp4, .mpe, .mpeg, .mpg, .numbers, .odg, .odp, .ods, .odt, .onepkg, .onetmp, .onetoc, .onetoc2, .oxps, .pages, .pdf, .png, .pot, .potm, .potx, .ppam, .pps, .ppsm, .ppsx, .ppt, .pptm, .pptx, .qt, .rar, .rtf, .rtx, .sldm, .sldx, .svg, .tar, .tif, .tiff, .tsv, .txt, .wav, .wax, .wma, .wri, .xla, .xlam, .xls, .xlsb, .xlsm, .xlsx, .xlt, .xltm, .xltx, .xlw, .xml, .xps, .zip, .ret, .rem, .ext
    sanitizer:
      experimental: false
      text:
        enabled: false
  bifrost:
    events:
      url: http://bifrostdev.whebdc.com.br:9090/bifrost/events
    tasy:
      url: http://bifrostdev.whebdc.com.br:9090/tasy
  spinal:
    server: srv-spinal-tech.whebdc.com.br:9092
    datasource: WTASY
    enabled: false
    domain: tasy
    name: backend
    kafka:
      servers: srv-spinal-tech.whebdc.com.br:9092
  smartcare:
    enabled: true
    url: http://srv-pform-01.whebdc.com.br:8080
  smartlink:
    backend-url: http://localhost:4443
    wallet-path: file:/foo/u01
    wallet-secret: secret-for-wallet
